# Generated by Django 3.1.5 on 2021-02-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxigeno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrador',
            name='ofrece_renta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concentrador',
            name='ofrece_venta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='dar_de_baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconcentrador',
            name='ofrece_renta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalconcentrador',
            name='ofrece_venta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldistribuidor',
            name='dar_de_baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltanque',
            name='ofrece_recarga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltanque',
            name='ofrece_renta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltanque',
            name='ofrece_venta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tanque',
            name='ofrece_recarga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tanque',
            name='ofrece_renta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tanque',
            name='ofrece_venta',
            field=models.BooleanField(default=True),
        ),
    ]