# Generated by Django 3.1.5 on 2021-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxigeno', '0002_auto_20210204_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='notas_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldistribuidor',
            name='notas_internas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
