# Generated by Django 3.1.5 on 2021-02-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxigeno', '0004_distribuidorpotencial_historicaldistribuidorpotencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='abre_24h',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='abre_fin_de_semana',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='recarga_gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldistribuidor',
            name='abre_24h',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldistribuidor',
            name='abre_fin_de_semana',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldistribuidor',
            name='recarga_gratis',
            field=models.BooleanField(default=False),
        ),
    ]
    