# Generated by Django 3.1.5 on 2021-02-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxigeno', '0005_auto_20210213_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidor',
            old_name='abre_fin_de_semana',
            new_name='abre_domingo',
        ),
        migrations.RenameField(
            model_name='historicaldistribuidor',
            old_name='abre_fin_de_semana',
            new_name='abre_domingo',
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='abre_sabado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldistribuidor',
            name='abre_sabado',
            field=models.BooleanField(default=True),
        ),
    ]