# Generated by Django 3.1.5 on 2021-03-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='horario',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='distribuidorpotencial',
            name='horario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
