# Generated by Django 3.1.5 on 2021-03-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0002_auto_20210322_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='name',
            new_name='nombre',
        ),
    ]
