# Generated by Django 3.1.5 on 2021-03-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0004_historicaldistribuidor_historicaldistribuidorpotencial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distribuidor',
            table='distribuidor',
        ),
        migrations.AlterModelTable(
            name='distribuidorpotencial',
            table='distribuidor_potencial',
        ),
    ]
