# Generated by Django 3.1.5 on 2021-04-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidores', '0005_auto_20210322_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='footer',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='estado',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
