# Generated by Django 3.1.5 on 2021-03-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_historicalconcentrador_historicaltanque'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concentrador',
            table='concentrador',
        ),
        migrations.AlterModelTable(
            name='tanque',
            table='tanque',
        ),
    ]
